# group_vars/flare_nodes.yml
---
# Disk configuration - use the correct device path from Terraform
disk_device: "/dev/disk/by-id/google-go-flare-data"
mount_point: "/data/go-flare"

# Flare node configuration
flare_config:
  api-admin-enabled: false
  api-auth-required: false
  api-keystore-enabled: false
  api-metrics-enabled: true
  chain-config-dir: "/app/conf"
  chain-data-dir: "/app/db"
  db-enabled: true
  http-host: "0.0.0.0"
  http-port: 9650
  log-dir: "/app/logs"
  log-level: "info"
  network-id: "costwo"
  public-ip-resolution-service: "opendns"
  snow-avalanche-batch-size: 30
  snow-avalanche-num-parents: 5
  snow-concurrent-repolls: 4
  snow-sample-size: 20
  staking-enabled: true
  staking-port: 9651
  state-sync-enabled: true
  # Enable state sync for faster bootstrap
  snow-mixed-query-num-push-vdr: 10
  consensus-shutdown-timeout: "30s"

# Optional features
use_distroless: false
verify_image_signature: false

# Version and directories
go_flare_version: "v1.11.0"
flare_config_dir: "/opt/flare/conf"
flare_logs_dir: "/opt/flare/logs"
node_workspace: "/opt/node"